package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    OpIterator child1;
    OpIterator child2;
    JoinPredicate joinPred;

    private static final long serialVersionUID = 1L;

    /**
     * Constructor. Accepts two children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, OpIterator child1, OpIterator child2) {
        // TODO: some code goes here
        this.joinPred = p;
        this.child1 = child1;
        this.child2 = child2;
    }

    public JoinPredicate getJoinPredicate() {
        // TODO: some code goes here
        return this.joinPred;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        // TODO: some code goes here
        return child1.getTupleDesc().getFieldName(joinPred.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        // TODO: some code goes here
        return child2.getTupleDesc().getFieldName(joinPred.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        // TODO: some code goes here
        return TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        // TODO: some code goes here
        super.open();
        this.child1.open();
        this.child2.open();
        this.outerTuple = child1.next();
    }

    public void close() {
        // TODO: some code goes here
        super.close();
        this.child1.close();
        this.child2.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        // TODO: some code goes here
        this.child1.rewind();
        this.child2.rewind();
        this.outerTuple = child1.next();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    private Tuple outerTuple;
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        // TODO: some code goes here
        if (!child1.hasNext() && !child2.hasNext()) return null;

        // Move outer child to next one, rewind inner child iterator
        if (child1.hasNext() && !child2.hasNext()) {
            this.outerTuple = child1.next();
            child2.rewind();
        }

        Tuple innerTuple = child2.next();
        TupleDesc nextTd = getTupleDesc();
        Tuple nextTuple = new Tuple(nextTd);

        // Filter over un-satisfied tuples
        while (!this.joinPred.filter(outerTuple, innerTuple)) {
            if (!child1.hasNext() && !child2.hasNext()) return null;
            if (child1.hasNext() && !child2.hasNext()) {
                this.outerTuple = child1.next();
                child2.rewind();
            }
            innerTuple = child2.next();
        }

        // Set up join tuple (i + j)
        for (int i = 0; i < outerTuple.fields.length; i++)
            nextTuple.setField(i, outerTuple.getField(i));
        for (int j = 0; j < innerTuple.fields.length; j++)
            nextTuple.setField(outerTuple.fields.length + j, innerTuple.getField(j));

        // System.out.println(nextTuple);

        return nextTuple;
    }

    @Override
    public OpIterator[] getChildren() {
        // TODO: some code goes here
        return new OpIterator[] {this.child1, this.child2};
    }

    @Override
    public void setChildren(OpIterator[] children) {
        // TODO: some code goes here
        this.child1 = children[0];
        this.child2 = children[1];
    }

}
